### ISSUE TITLE
source ziti in deployment image

### ISSUE THREAD

**Issue by qrkourier** [dariuszSki/ziti-agent-wh#2]
This change will help to avoid confusion about which version of ziti is installed.

ref: https://github.com/openziti/ziti/blob/release-next/dist/docker-images/ziti-controller/Dockerfile

If the image will use `ziti` CLI, even if it will not be based on the RedHat UBI, then we can add a build stage in our Dockerfile that sources a pinned ziti version.

example Dockerfile

```dockerfile
ARG ZITI_CLI_TAG="latest"
ARG ZITI_CLI_IMAGE="docker.io/openziti/ziti-cli"

# this builds docker.io/openziti/ziti-k8s-agent
FROM ${ZITI_CLI_IMAGE}:${ZITI_CLI_TAG}

# set up image as root
USER root

# do stuff as root
RUN chmod 0755 /usr/local/bin/ziti-agent-wh

# drop privs to ziggy
USER ziggy
COPY ${DOCKER_BUILD_DIR}/deployment/bashrc /home/ziggy/.bashrc
ENTRYPOINT [ "ziti-agent-wh" ]
```

**Comment by dariuszSki** [comment]
ok, sounds good. Thanks

**Comment by dariuszSki** [comment]
updated it. This change makes sense.
